@boardUrl=http://localhost:8080/board

@server = http://localhost:8080

### 게시글 화면 (쿼리 없음)
GET {{boardUrl}}?pageNum=1
# 기본적으로 pageNum이 1이여야 한다.

### 게시글 화면 (쿼리 있음)
GET {{boardUrl}}/?boardSeq=3

### 게시글 검색
GET {{boardUrl}}?search=제목

### 게시글 검색 ( + 페이징 처리)
GET {{boardUrl}}/?search=제목&pageNum=4

### 게시물 삭제
DELETE {{boardUrl}}/remove
Content-Type: application/json; charset=UTF-8

{
    "boardSeq" : 3
}

### 게시글 등록 화면
GET {{boardUrl}}/register

### 게시글 등록
POST {{boardUrl}}/register
Content-Type: multipart/form-data; boundary=postRegister

--postRegister
Content-Disposition: form-data; name="data"

{
  "title": "제목 Test",
  "content": "내용 Test",
  "userSeq": 1
}

# --postRegister
# Content-Disposition: form-data; name="uploadFile"; filename="postRegister.pdf"
# Content-Type: application/pdf
# Content-Type: image/jpeg

# 이미지
# < C:\SeSAC\polar_bear.jpg
# < /Users/user/Desktop/애플1692602940472.png

# 파일
# < C:\SeSAC\test.pdf
# < C:\SeSAC\Prettier 설정하기.pdf

--postRegister--

### 게시글 수정 화면
GET {{boardUrl}}/modify
Content-Type: application/json; charset=UTF-8

{
  "boardSeq": "18"
}

### 게시글 수정
PATCH {{boardUrl}}/modify
Content-Type: multipart/form-data; boundary=patchRegister

--patchRegister
Content-Disposition: form-data; name="data"

{
  "title": "제목 ::: 수정 :::  Test",
  "content": "내용 ::: 수정 ::: Test",
  "boardSeq": "3"
}

--patchRegister
Content-Disposition: form-data; name="uploadFile"; filename="patchRegister.pdf"
Content-Type: application/pdf
# Content-Type: image/jpeg

# 이미지
# < C:\SeSAC\laser4.jpg
# < /Users/user/Desktop/애플1692602940472.png

# 파일
< C:\SeSAC\Prettier 설정하기 - 복사본.pdf

--patchRegister--