@server = http://localhost:8080

### 회원 가입 처리
POST {{server}}/user/signup
Content-Type: application/json; charset=UTF-8

{
    "registerName": "손흥민",
    "registerEmail": "123@naver.com",
    "registerPw": "1234"
}

### 이메일(아이디) 중복 확인
POST {{server}}/user/checkEmail
Content-Type: application/json; charset=UTF-8

{
    "registerEmail": "123@naver.com"
}

### 로그인 처리
POST {{server}}/user/signin
Content-Type: application/json; charset=UTF-8

# 김철수(Web 리더, AI 팀원)
# {
#   "loginEmail": "sesac-k@gmail.com",
#   "loginPw": "aaaassss1111!!!!"
# }

# 홍길동(Web 팀원)
# {
#   "loginEmail": "sesac-h@gmail.com",
#   "loginPw": "aaaassss1111!!!!"
# }

# 박영희(App 리더, Web 팀원)
# {
#   "loginEmail": "sesac-p@gmail.com",
#   "loginPw": "aaaassss1111!!!!"
# }

# 손흥민(Web,App 팀원 / AI 리더)
{
  "loginEmail": "sesac-s@gmail.com",
  "loginPw": "aaaassss1111!!!!"
}

# 이재성(App 팀원)
# {
#   "loginEmail": "sesac-l@gmail.com",
#   "loginPw": "aaaassss1111!!!!"
# }

### 로그아웃 처리
GET {{server}}/user/logout
