@server = http://localhost:8080

### 회원 가입 처리
POST {{server}}/user/signup
Content-Type: application/json; charset=UTF-8

{
    "registerName": "손흥민",
    "registerEmail": "123@naver.com",
    "registerPw": "1234"
}

### 닉네임 중복 확인
POST {{server}}/user/checkName
Content-Type: application/json; charset=UTF-8

{
    "registerName": "가나다"
}

### 이메일(아이디) 중복 확인
POST {{server}}/user/checkEmail
Content-Type: application/json; charset=UTF-8

{
    "registerEmail": "123@naver.com"
}

### 로그인 처리
POST {{server}}/user/signin
Content-Type: application/json; charset=UTF-8

# 김철수(Web 리더, AI 팀원)
# {
#   "loginEmail": "sesac-k@gmail.com",
#   "loginPw": "aaaassss1111!!!!"
# }

# 최번개(Web 팀원)
# {
#   "loginEmail": "sesac-c@gmail.com",
#   "loginPw": "aaaassss1111!!!!"
# }

# 박영희(App 리더(모집 마감), Web 팀원)
# {
#   "loginEmail": "sesac-p@gmail.com",
#   "loginPw": "aaaassss1111!!!!"
# }

# 손흥민(Web,App(모집 마감) 팀원 / AI 리더 / 임의 1개(Web) : 모집중, 임의 1개(Web) : 모집 마감)
# {
#   "loginEmail": "sesac-s@gmail.com",
#   "loginPw": "aaaassss1111!!!!"
# }

# 이재성(App 팀원(모집 마감))
# {
#   "loginEmail": "sesac-l@gmail.com",
#   "loginPw": "aaaassss1111!!!!"
# }

# 관리자
# {
#     "loginEmail": "admin@sesac.com",
#     "loginPw": "sesac123!@#"
# }

### 로그아웃 처리
GET {{server}}/user/logout

### 유저 프로필 수정
PATCH {{server}}/user/modify
Content-Type: application/json; charset=UTF-8

{
    "newPassword": "Aabcd1234!",
    "confirmPassword": "Aabcd1234!"
}
